---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: spos-lang
  name: spos-lang
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: spos_mapping
      grpc: true
      prefix: /spos.Lang/
      rewrite: /spos.Lang/
      service: spos-lang
      timeout_ms: 20000
#        - descriptor: A test case
#          headers:
#            - "x-ambassador-test-allow"
spec:
  type: NodePort
  ports:
  - port: 80
    name: spos-lang
    targetPort: spos-api
  selector:
    service: spos-lang
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spos-lang
spec:
  replicas: 5
  template:
    metadata:
      labels:
        service: spos-lang
    spec:
      containers:
      - name: spos-lang
        image: patlihh/spos-lang:v1.0
        ports:
        - name: spos-api
          containerPort: 9998
        env:
          - name: PORT
            value: "9998"
          - name: http_proxy
            value: "http://192.168.20.7:30080"   
          - name: https_proxy
            value: "http://192.168.20.7:30080"
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /credential.json		
          - name: WORDPRESS_DB_PASSWORD
            value: "Unitone@2018"
          - name: WORDPRESS_DB_HOST
            value: "192.168.20.107"				

      restartPolicy: Always
