---
apiVersion: v1
kind: Service
metadata:
  name: spos-auth
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  AuthService
      name:  authentication
      auth_service: "spos-auth:3000"
      path_prefix: "/extauth"
      allowed_headers:
      - "x-qotm-session"
spec:
  type: NodePort
  selector:
    app: spos-auth
  ports:
  - port: 3000
    name: http-spos-auth
    targetPort: spos-auth-api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spos-auth
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spos-auth
    spec:
      containers:
      - name: spos-auth
        image: patlihh/spos-auth:v1.0 
#        env:
#        - name: WORDPRESS_DB_HOST
#          value: wordpress-mysql
#        - name: WORDPRESS_DB_PASSWORD
#          valueFrom:
#            secretKeyRef:
#              name: mysql-pass
#              key: password
        ports:
        - name: spos-auth-api
          containerPort: 3000
        resources:
          limits:
            cpu: "0.1"
            memory: 100Mi
